CREATE DATABASE IF NOT EXISTS confeitaria CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE confeitaria;

CREATE TABLE IF NOT EXISTS ingrediente (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL UNIQUE,
  unidade_medida VARCHAR(20) NOT NULL,
  quantidade_atual DECIMAL(10,2) NOT NULL DEFAULT 0,
  estoque_minimo DECIMAL(10,2) NOT NULL DEFAULT 0,
  preco_unitario DECIMAL(10,2) NOT NULL DEFAULT 0,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS receita (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  descricao TEXT,
  rendimento INT NOT NULL DEFAULT 1,
  tempo_preparo INT NOT NULL DEFAULT 0,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  data_cadastro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS receita_ingrediente (
  id INT AUTO_INCREMENT PRIMARY KEY,
  receita_id INT NOT NULL,
  ingrediente_id INT NOT NULL,
  quantidade DECIMAL(10,2) NOT NULL,
  unidade VARCHAR(20) NOT NULL,
  CONSTRAINT fk_ri_receita FOREIGN KEY (receita_id) REFERENCES receita(id),
  CONSTRAINT fk_ri_ingrediente FOREIGN KEY (ingrediente_id) REFERENCES ingrediente(id)
);

CREATE TABLE IF NOT EXISTS pedido (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cliente VARCHAR(150) NOT NULL,
  data_pedido DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_entrega DATETIME NULL,
  status ENUM('PENDENTE','EM_PRODUCAO','CONCLUIDO','CANCELADO') NOT NULL DEFAULT 'PENDENTE',
  valor_total DECIMAL(10,2) NOT NULL DEFAULT 0,
  custo_total DECIMAL(10,2) NOT NULL DEFAULT 0,
  observacao VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS pedido_item (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pedido_id INT NOT NULL,
  receita_id INT NOT NULL,
  quantidade INT NOT NULL,
  valor_unitario DECIMAL(10,2) NOT NULL,
  subtotal DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (pedido_id) REFERENCES pedido(id),
  FOREIGN KEY (receita_id) REFERENCES receita(id)
);

CREATE TABLE IF NOT EXISTS estoque_movimentacao (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tipo ENUM('ENTRADA','SAIDA') NOT NULL,
  quantidade DECIMAL(10,2) NOT NULL,
  data_hora DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  motivo VARCHAR(255) NOT NULL,
  ingrediente_id INT NOT NULL,
  FOREIGN KEY (ingrediente_id) REFERENCES ingrediente(id)
);

CREATE TABLE IF NOT EXISTS lancamento_financeiro (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tipo ENUM('RECEITA','DESPESA') NOT NULL,
  categoria VARCHAR(100) NOT NULL,
  descricao VARCHAR(1000) NOT NULL,
  valor DECIMAL(10,2) NOT NULL,
  data_lancamento DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  pedido_id INT NULL,
  FOREIGN KEY (pedido_id) REFERENCES pedido(id)
);
